---
samples_orig_names:
    immature: "GFP_EPCR_LSKs_RNA"
    diverse: "GFP_Viable_RNA"
raw_dir: "data/raw"
interim_dir: "data/interim"
output_dir: "data/processed"
report_dir: "reports"
docs_dir: "docs"
data_owner: "DB_QZ"
project_name: "DB_QZ_multiome"
n_threads: 16
celltag_version: "3"
seed: 12345
