---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.14.4
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
start_time <- Sys.time()
start_time
```

# Pseudotime

```{r}
source("helpers.R")
source("pseudotime_helpers.R")
```

```{r}
str_glue("- project_path: {project_path}")
str_glue("- output_dir: {output_dir}")
str_glue("- plot_dir: {plot_dir}")
str_glue("- seed: {seed}")
```

```{r}
library(tictoc)
library(rjson)
```

```{r}
inputs <- c(
  "post_SAILERX_rds" = str_glue("{output_dir}seurat_object_post_SAILERX.rds"),
  "sailerx_cluster_colours" = str_glue("{output_dir}sailerx_cluster_colours")
)
outputs <- c(
  "trajectory_lineages" = str_c(output_dir, "trajectory_lineages.json")
)
```

```{r}
"inputs:"
inputs
"outputs:"
outputs
```

```{r}
colours_features <- c("moccasin", "darkslategray")
colours_features
```

---


# Load data

```{r}
sobj <- readRDS(inputs["post_SAILERX_rds"])
```

```{r}
sobj
```

```{r}
n_clusters <- (sobj[["sailerx_clusters"]] %>% unique() %>% dim())[1]
```

```{r}
sailerx_colours <- read.table(inputs[["sailerx_cluster_colours"]])$V2
names(sailerx_colours) <- 0:(length(sailerx_colours) - 1)
sailerx_colours
```

```{r}
DimPlot(sobj, group.by = "sailerx_clusters", pt.size = .8, cols = sailerx_colours, label = T, label.box = T) + coord_fixed()
```

```{r}
start_cluster <- 5
```

# Slingshot

```{r}
sce_sobj <- sobj %>% as.SingleCellExperiment
```

```{r}
sce_sobj
```

```{r}
sce_sobj %>% colData() %>% str()
```

```{r}
# Need to do conversion to dataframe (or smth else) in order to see contents of DFrame in jupyter, verry annoying
sce_sobj %>%
  colData() %>%
  as.data.frame() %>%
  head()
```

```{r tags=c()}
sce_sobj %>% colData() %>% as_tibble %>% pull("sailerx_clusters")
```

```{r tags=c()}
colData(sce_sobj)[["sailerx_clusters"]]
```

```{r}
do_sling <- function(sce_sobj = sce_sobj, end_cluster = NULL, start_cluster = start_cluster) {
  sce <-
    slingshot(
      data = sce_sobj,
      clusterLabels = colData(sce_sobj)[["sailerx_clusters"]], # %>% as.integer,
      reducedDim = "UMAP_SAILERX",
      start.clus = start_cluster,
      end.clus = end_cluster
    )
  return(sce)
}
```

```{r}
end_clusters <- c(4, 1, 6, 7) %>% as.character
```

```{r}
sce_all <- do_sling(
  sce_sobj = sce_sobj,
  start_cluster = start_cluster,
  end_cluster = end_clusters
)

sce_all
```

```{r}
sce_all <- do_sling(
  sce_sobj = sce_sobj,
  start_cluster = start_cluster,
  end_cluster = end_clusters
)

sce_all
```

```{r}
foo <- \(end_cluster) {
  sds <- sce[[as.character(end_cluster)]]

  nc <- 2
  pt <- slingPseudotime(sds)
  nms <- colnames(pt)
  nr <- ceiling(length(nms) / nc)
  pal <- viridis(100, end = 0.95)
  par(mfrow = c(nr, nc))
  for (i in nms) {
    colors <- pal[cut(pt[, i], breaks = 100)]
    plot(reducedDims(sce_all)$UMAP_SAILERX, pch = 16, col = rgb(
      red = .6, green = .6, blue = .6, alpha = .7
    ), asp = 1)
    points(reducedDims(sds)$UMAP_SAILERX,
      col = colors,
      pch = 16, cex = 0.5, asp = 1
    )
    lines(SlingshotDataSet(sds), lwd = 2, col = "black") # , type = 'lineages')
  }
}
```

```{r}
sds <- sce_all

nc <- 2
pt <- slingPseudotime(sds)
nms <- colnames(pt)
nr <- ceiling(length(nms)/nc)
pal <- viridis(100, end = 0.95)
par(mfrow = c(nr, nc))
for (i in nms) {
  colors <- pal[cut(pt[,i], breaks = 100)]
  plot(reducedDims(sce_all)$UMAP_SAILERX, pch = 16, col = rgb(red = .6, green = .6, blue = .6, alpha = .7), asp = 1)
  # plot(reducedDims(sds)$UMAP_SAILERX, pch = 16, main = i, col = rgb(red = .6, green = .6, blue = .6, alpha = .7), asp = 1)
  points(reducedDims(sds)$UMAP_SAILERX, col = colors, pch = 16, cex = 0.5, asp = 1)
  lines(SlingshotDataSet(sds), lwd = 2, col = 'black')#, type = 'lineages')
}
```

```{r}
lineages <- c(1, 4, 7, 6) %>% as.character
lineages
```

```{r}
nms
```

```{r}
pt %>% head
```

# Find features correlating with trajectories' pseudotime

```{r}
sce <- sce_all
```

```{r tags=c()}
colData(sce)$slingshot
```

```{r tags=c()}
colData(sce)$slingshot %>% metadata %>% names
```

```{r}
sce@colData %>% head
```

```{r}
pseudotimes_of_interest <- list()
i <- 1
for (cluster in c(4, 1, 6, 7) %>% as.character()) {
  pseudotimes_of_interest[[cluster]] <- sce@colData[[str_c("slingPseudotime_", i)]]
  i <- i + 1
}
```

```{r tags=c()}
lapply(pseudotimes_of_interest, head)
```

```{r tags=c()}
correlations <- list()
for (end_cluster in names(pseudotimes_of_interest)) {
  tic(end_cluster)
  correlations[[end_cluster]] <- mclapply(
    seq_len(length(VariableFeatures(sobj))),
    FUN = \(i) {
      x <- pseudotimes_of_interest[[end_cluster]]
      y <- sobj[["RNA"]]@data[VariableFeatures(sobj)[i], colnames(sce)]
      result <- cor.test(x, y)
      result$estimate %>% as.numeric %>% return()
    },
    mc.cores = 16
  ) %>% as.numeric
  toc()
}
```

```{r}
lapply(lapply(pseudotimes_of_interest, is.na), table)
```

```{r}
plot(correlations[["4"]] %>% length %>% seq_len, correlations[["4"]])
```

```{r}
lapply(names(pseudotimes_of_interest), FUN = \(i) correlations[[i]] %>% summary)
```

---


# Plot trajectories

```{r}
slingplot <- function(sce,
                      reduction = "UMAP_SAILERX",
                      palette = "viridis",
                      line_type = NULL,
                      subset = FALSE,
                      start_cluster = start_cluster,
                      end_cluster = -1,
                      title = "Pseudotime + Trajectories") {
  if (str_to_title(palette) %in% hcl.pals()) {
    colors <- hcl.colors(n = 50, palette = palette)
  }
  end_cluster <- end_cluster %>% as.character()
  plot(#reducedDims(sce),
    reducedDims(sce)[[reduction]],
    pch = 16, col = rgb(
      red = .6, green = .6, blue = .6, alpha = .7
    ), asp = 1
  )
  points(
    reducedDims(sce)[[reduction]],
    col = colors[
      cut(
        sce[[
          str_c("slingPseudotime_", which(lineages == end_cluster))
        ]],
        breaks = 50
      )
    ], pch = 16, asp = 1
  )
  lines(SlingshotDataSet(sce), lwd = 2, type = line_type)
  title(title)
  # legend("bottomleft",
  #   #legend = str_flatten_comma(included_clusters),
  #   title = "Clusters included:"
  # )
  legend("topleft", legend = end_cluster, title = "End cluster:")
}
```

```{r}
lapply(c(4, 1, 6, 7), FUN = \(c) {
  slingplot(
    sce_all,
    end_cluster = c
  )
})
```

```{r}
correlation_plot(end_cluster)
```

```{r}
lapply(c(4, 1, 6, 7), FUN = \(c) {
  correlation_plot(
    end_cluster = c
  )
})
```

```{r}
# end_cluster <- as.character(end_cluster)
# quantil <- quantile(
#   abs(correlations[[end_cluster]]),
#   probs = quant, na.rm = T
# )
# highest_features <- VariableFeatures(sobj)[which(abs(correlations[[end_cluster]]) > quantil)]
# slingshot_df <- colData(sce[[traj_dict[[end_cluster]][["lvl1"]]]])
# slingshot_df[["slingshot"]] <- NULL
# slingshot_df <- slingshot_df %>% as.data.frame
```

```{r}
# slingshot_df %>% as.list %>% lapply(., FUN = \(x) class(x))
```

```{r}
# slingshot_df %>% names
```

## Pseudotime heatmaps

```{r}
do_heatmap <- function(features = VariableFeatures(sobj),
                       slingshot_df,
                       use_raster = FALSE,
                       slot_to_use = "data",
                       show_row_names = TRUE,
                       cluster_features = FALSE,
                       supplied_data = NULL) {
  if (!is.null(supplied_data)) {
    mat_to_use <- supplied_data
  } else {
    mat_to_use <- slot(sobj@assays$RNA, slot_to_use)
  }
  subset_matrix <- mat_to_use[
    features,
    slingshot_df$barcodes
  ] %>%
    as.matrix()
  col_fun <- colorRamp2(
    c(0, quantile(subset_matrix, probs = c(0.99))[[1]]),
    c("darkblue", "green")
  )
  present_clusters <- unique(slingshot_df$sailerx_clusters)
  n_clusters <- (sobj[["sailerx_clusters"]] %>% unique() %>% dim())[1]
  # sailerx_colours
  # sailerx_colours <- palette.colors(
  #   n = length(0:8), palette = "Classic Tableau"
  # )
  # names(sailerx_colours) <- as.character(0:8)
  cluster_annotation <- HeatmapAnnotation(
    df = slingshot_df["sailerx_clusters"],
    name = "sailerx_clusters",
    col = list(sailerx_clusters = sailerx_colours[present_clusters]),
    annotation_legend_param = list(
      legend_direction = "horizontal",
      title_position = "lefttop-rot"
    )
  )
  return(
    Heatmap(
      mat = subset_matrix,
      show_column_names = F,
      show_row_names = show_row_names,
      cluster_rows = cluster_features,
      cluster_columns = F,
      use_raster = use_raster,
      col = col_fun,
      column_title = "Cells ordered by pseudotime -->",
      row_title = "Features",
      heatmap_legend_param = list(
        title = "Expression",
        title_position = "lefttop-rot"
      ),
      border_gp = gpar(col = "black", lty = "solid"),
      column_order = slingshot_df$barcodes,
      top_annotation = cluster_annotation
    )
  )
}

correlation_plot <- function(end_cluster = NULL, quant = 0.90) {
  assert_that(!is.na(end_cluster))
  end_cluster <- as.character(end_cluster)
  quantil <- quantile(
    abs(correlations[[end_cluster]]),
    probs = quant, na.rm = T
  )
  ggplot(
    data.frame(
      "cor" = correlations[[end_cluster]],
      "high" = abs(correlations[[end_cluster]]) > quantil
    ),
    aes(seq_along(cor), y = cor, color = as.factor(high))
  ) +
    geom_line(
      mapping = aes(y = quantil),
      color = "gray20", linetype = "dashed"
    ) +
    geom_line(
      mapping = aes(y = -quantil),
      color = "gray20", linetype = "dashed"
    ) +
    geom_point() +
    scale_color_manual(
      values = c("darkgray", "maroon"),
      name = str_c("Over ", quant * 100, "% abs()"),
      breaks = c(F, T)
    ) +
    ggtitle(str_c(
      "Pseudotime correlation with features for\ntrajectory with end_cluster ",
      end_cluster
    )) +
    xlab("Variable features / HVGs") +
    ylab("Correlation with pseudotime") +
    theme(
      plot.title = element_text(face = "bold", size = 15),
      axis.line = element_line()
    ) +
    coord_fixed(ratio = 2e3)
}

correlation_heatmap <- function(sce = sce_all,
                                end_cluster = 4,
                                quant = .98,
                                slot_to_use = "scale.data",
                                use_raster = FALSE,
                                cluster_features = TRUE,
                                supplied_data = NULL) {
  end_cluster <- as.character(end_cluster)
  quantil <- quantile(
    abs(correlations[[end_cluster]]),
    probs = quant, na.rm = T
  )
  highest_features <-
    VariableFeatures(sobj)[which(abs(correlations[[end_cluster]]) > quantil)]
  slingshot_df <- colData(sce)
  slingshot_df[["slingshot"]] <- NULL
  slingshot_df <- slingshot_df %>% as.data.frame()
  slingshot_df <- as.data.frame(list(
    "barcodes" = rownames(slingshot_df),
    "sailerx_clusters" = slingshot_df$sailerx_clusters,
    "pseudotime" = slingPseudotime(
      sce
    )[, str_c("Lineage", which(lineages == end_cluster))]
    # "pseudotime" = slingshot_df[[str_c("slingPseudotime_",
    # traj_dict[[end_cluster]][["lvl2"]])]]
    # "pseudotime" = pseudotimes_of_interest[[end_cluster]]
  )) %>%
    arrange(pseudotime) %>%
    drop_na()
  do_heatmap(highest_features,
    slingshot_df = slingshot_df,
    slot_to_use = slot_to_use,
    use_raster = use_raster,
    cluster_features = cluster_features,
    supplied_data = supplied_data
  ) +
    labs(caption = end_cluster)
}

trajectory_plot <- function(sce = sce_all, end_cluster) {
  sds <- sce
  nc <- 1
  pt <- slingPseudotime(sds)
  nms <- colnames(pt)
  nr <- ceiling(length(nms) / nc)
  pal <- viridis(100, end = 0.95)
  # par(mfrow = c(nr, nc))
  # z <- traj_dict[[as.character(end_cluster)]][["lvl2"]] %>% as.numeric()
  z <- str_c("Lineage", which(lineages == end_cluster))
  i <- nms[z]
  colors <- pal[cut(pt[, i], breaks = 100)]
  plot(reducedDims(sce_all)$UMAP_SAILERX,
    pch = 16, col = rgb(red = .6, green = .6, blue = .6, alpha = .7), asp = 1
  )
  # plot(reducedDims(sds)$UMAP_SAILERX, pch = 16, main = i, col = rgb(red = .6,
  # green = .6, blue = .6, alpha = .7), asp = 1)
  points(reducedDims(sds)$UMAP_SAILERX,
    col = colors, pch = 16, cex = 0.5, asp = 1
  )
  lines(SlingshotDataSet(sds), lwd = 2, col = "black") # , type = 'lineages')
}
```

```{r tags=c()}
correlation_heatmap(end_cluster = 1)
```

```{r tags=c()}
correlation_heatmap(end_cluster = 1, cluster_features = F)
```

```{r tags=c()}
correlation_heatmap(end_cluster = 1, slot_to_use = "data", cluster_features = T)
```

```{r tags=c()}
correlation_heatmap(end_cluster = 1, slot_to_use = "data", cluster_features = T)
```

```{r}
correlation_heatmap(end_cluster = 1, slot_to_use = "data", cluster_features = F)
```

With clustering and slot scale.data is best.

---


### Final versions of heatmaps

```{r tags=c()}
correlation_heatmap(end_cluster = 4)
```

```{r tags=c()}
correlation_heatmap(end_cluster = 1)
```

```{r tags=c()}
correlation_heatmap(end_cluster = 6)
```

```{r tags=c()}
correlation_heatmap(end_cluster = 7)
```

---


# Save plots and data

```{r}
plot_dir
```

```{r}
slingplot(sce, end_cluster = 1)
```

```{r}
Sys.sleep(1)
```

```{r}
for (end_cluster in end_clusters) {
  print(end_cluster)
  print(str_glue("{plot_dir}{end_cluster}_pt_umap.svg"))

  svg(filename = str_glue("{plot_dir}{end_cluster}_pt_umap.svg"), width = 7, height = 7)
  slingplot(
    sce,
    end_cluster = end_cluster
  )
  dev.off()

  ggsave(
    plot = correlation_plot(end_cluster),
    filename = str_glue("{plot_dir}{end_cluster}_pt_corr_scatter.svg"),
    device = "svg",
    units = "in",
    width = 7,
    height = 7
  )

  svg(
    filename = str_glue("{plot_dir}{end_cluster}_pt_corr_heatmap.svg"),
    width = 9,
    height = 11
  )
  p <- correlation_heatmap(end_cluster = end_cluster, use_raster = T)
  p %>% draw()
  dev.off()

  quant <- .995
  quantil <- quantile(
    abs(correlations[[as.character(end_cluster)]]),
    probs = quant, na.rm = T
  )
  highest_features <- VariableFeatures(sobj)[which(abs(correlations[[as.character(end_cluster)]]) > quantil)]

  ggsave(
    plot = FeaturePlot(
      sobj,
      reduction = "UMAP_SAILERX",
      features = highest_features[1:4],
      coord.fixed = T,
      cols = colours_features
    ),
    filename = str_glue("{plot_dir}{end_cluster}_pt_corr_featureplot_top1-4.svg"),
    device = "svg",
    units = "in",
    width = 7,
    height = 7
  )

  ggsave(
    plot = FeaturePlot(
      sobj,
      reduction = "UMAP_SAILERX",
      features = highest_features[5:8],
      coord.fixed = T,
      cols = colours_features
    ),
    filename = str_glue("{plot_dir}{end_cluster}_pt_corr_featureplot_top5-8.svg"),
    device = "svg",
    units = "in",
    width = 7,
    height = 7
  )
}
```

```{r}
system(str_glue("wc -l {plot_dir}{end_cluster}_pt_corr_heatmap.svg"), intern = T)
```

```{r}
system(str_glue("wc -l {plot_dir}{end_cluster}_pt_corr_featureplot_top1-4.svg"), intern = T)
```

---


# Misc.


---

## One plot to rule them all

```{r}
defining_genes <- c("Mfsd2b", "Mecom", "Ngp", "F13a1", "Cd200r3") %>% str_to_title
stopifnot(all(defining_genes %in% rownames(sobj[["RNA"]])))
```

```{r}
FeaturePlot(sobj, features = defining_genes, coord.fixed = T, cols = colours_features)
```

```{r}
FeaturePlot(sobj, features = defining_genes, coord.fixed = T, cols = colours_features)
```

```{r}
FeaturePlot(sobj, features = defining_genes, coord.fixed = T, order = T, cols = colours_features)
```

---

## Cell Cycle plot

```{r}
sobj[[]] %>% head
```

```{r}
p <- DimPlot(sobj, group.by = "Phase", pt.size = 1, shuffle = T, cols = c("gray70", "orangered3", "royalblue4")) + coord_fixed()
p
```

```{r}
ggsave(plot = p, filename = str_c(plot_dir, "umap_cc_phase.svg"), device = "svg", units = "in", width = 7, height = 7)
```

---

## Export lineage curves for grand umap

```{r}
(
  sce %>%
    SlingshotDataSet() %>%
    getCurves()
)@metadata$curves$Lineage1$s %>%
  plot()
```

```{r}
traj_lineages <- list()
for (trajectory in end_clusters) {
  lineage_id <- str_c("Lineage", which(lineages == trajectory))
    
  df <- SlingshotDataSet(sce)@curves[[lineage_id]]$s %>% as.data.frame()
  # df <- getCurves(SlingshotDataSet(sce))@metadata$curves[[str_c("Lineage", lineage_nbr)]]$s %>% as.data.frame()
  # (sce[["8"]] %>% SlingshotDataSet)@curves
  names(df) <- c("xend", "yend")
  df <- df %>% as_tibble()
    
  df2 <- df %>%
    as_tibble() %>%
    add_row(.before = 1)
  df <- df %>%
    as_tibble() %>%
    add_row()
  names(df2) <- c("x", "y")
    
  data_lines <- data.frame(
    x = df2$x,
    y = df2$y,
    xend = df$xend,
    yend = df$yend
  ) %>% as_tibble()
  data_lines <- data_lines %>%
    drop_na()
  traj_lineages[[trajectory]] <- data_lines
}
```

```{r}
lapply(traj_lineages, head)
```

```{r}
write(toJSON(traj_lineages), file = outputs[["trajectory_lineages"]])
```

---

```{r}
Sys.time()
```
